from setuptools import setup

setup(
    name="rl-toolkit",
    version="3.0",
    description="The RL-Toolkit: A toolkit for developing and comparing your reinforcement learning agents in various games (OpenAI Gym or Pybullet).",  # noqa
    url="https://github.com/markub3327/rl-toolkit",
    author="Martin Kubovčík",
    author_email="markub3327@gmail.com",
    license="mit",
    packages=["rl-toolkit"],
    keywords=[
        "reinforcement-learning",
        "ml",
        "openai-gym",
        "pybullet",
        "reverb",
        "docker",
        "rl-agents",
        "rl",
        "sac",
        "rl-algorithms",
        "soft-actor-critic",
        "gsde",
        "rl-toolkit",
        "games",
        "tensorflow",
        "wandb",
    ],
    install_requires=[
        "gym",
        "box2d",
        "pybullet",
        "tensorflow",
        "tensorflow_probability",
        "opencv-python",
        "wandb",
        "dm-reverb",
    ],
    python_requires=">=3.8",
    classifiers=[
        "License :: OSI Approved :: MIT License",
        "Environment :: Console",
        "Environment :: GPU :: NVIDIA CUDA",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Education",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
)
