# Database
port: 8000

# Agent
env_steps: 8
warmup_steps: 10000

# Learner
max_steps: 1000000
gamma: 0.99
tau: 0.01
min_replay_size: 10000
max_replay_size: 1000000
samples_per_insert: 32
batch_size: 256
log_interval: 1000

# Paths
save_path: "./save/model"
db_path: "./save/db"

# Actor model
Actor:
  units: [400, 300]
  init_noise: -3.0
  learning_rate: !!float 7.3e-4

# Critic model
Critic:
  count: 5
  units: [400, 300]
  n_quantiles: 35
  top_quantiles_to_drop: 3
  learning_rate: !!float 7.3e-4

# Alpha parameter
Alpha:
  learning_rate: !!float 7.3e-4
  init: 1.0