Server:
  # Database
  port: 8000

# Agent process
Agent:
  env_steps: 8
  warmup_steps: 10000

# Learner process
Learner:
  train_steps: 1000000
  max_replay_size: 1000000
  samples_per_insert: 32
  batch_size: 256
  # Actor model
  Actor:
    units: [512, 256]
    init_noise: -3.0
    learning_rate: !!float 7.3e-4
    clip_mean_min: -2.0
    clip_mean_max: 2.0
    global_clipnorm: 1.0
  # Critic model
  Critic:
    count: 5
    units: [512, 512, 256]
    merge_index: 1
    n_quantiles: 35
    top_quantiles_to_drop: 3
    gamma: 0.99
    tau: 0.01
    learning_rate: !!float 7.3e-4
    global_clipnorm: 1.0
  # Alpha parameter
  Alpha:
    init: 1.0
    learning_rate: !!float 7.3e-4

# Paths
save_path: "./save/model"
db_path: "./save/db"
